// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/articles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Articles"
                ],
                "summary": "获取文章列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article.ArticleListResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Articles"
                ],
                "summary": "发布新文章",
                "parameters": [
                    {
                        "description": "文章内容",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/article.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"id\": \"uuid\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/article.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/articles/{id}": {
            "get": {
                "tags": [
                    "博客接口"
                ],
                "summary": "获取特定 ID 的博客",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"1\"",
                        "description": "博客ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/article.Article"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/article.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/article.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "资源接口"
                ],
                "summary": "上传资源",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/asset.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "资源接口"
                ],
                "summary": "上传资源文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/upload.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/upload.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "article.Article": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "content": {
                    "description": "omitempty 表示列表时不展示正文",
                    "type": "string"
                },
                "createdAt": {
                    "description": "小驼峰",
                    "type": "string"
                },
                "defaultMode": {
                    "description": "小驼峰",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "小驼峰",
                    "type": "string"
                }
            }
        },
        "article.ArticleListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "必须叫 items",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/article.Article"
                    }
                }
            }
        },
        "article.CreateRequest": {
            "type": "object",
            "required": [
                "author",
                "category",
                "content",
                "defaultMode",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string",
                    "example": "负责人"
                },
                "category": {
                    "type": "string",
                    "example": "技术分享"
                },
                "content": {
                    "type": "string",
                    "example": "# Markdown 内容"
                },
                "defaultMode": {
                    "description": "@Enums article, slide, homework",
                    "type": "string",
                    "enum": [
                        "article",
                        "slide",
                        "homework"
                    ],
                    "example": "article"
                },
                "title": {
                    "type": "string",
                    "example": "关于后端严谨性的深度思考"
                }
            }
        },
        "article.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "参数校验失败"
                }
            }
        },
        "asset.SuccessResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "upload.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "错误描述"
                }
            }
        },
        "upload.UploadResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "上传成功"
                },
                "url": {
                    "type": "string",
                    "example": "/uploads/images/2026/03/25/uuid.png"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
