definitions:
  article.Article:
    properties:
      author:
        type: string
      category:
        type: string
      content:
        description: omitempty 表示列表时不展示正文
        type: string
      createdAt:
        description: 小驼峰
        type: string
      defaultMode:
        description: 小驼峰
        type: string
      id:
        type: string
      title:
        type: string
      updatedAt:
        description: 小驼峰
        type: string
    type: object
  article.ArticleListResponse:
    properties:
      items:
        description: 必须叫 items
        items:
          $ref: '#/definitions/article.Article'
        type: array
    type: object
  article.CreateRequest:
    properties:
      author:
        example: 负责人
        type: string
      category:
        example: 技术分享
        type: string
      content:
        example: '# Markdown 内容'
        type: string
      defaultMode:
        description: '@Enums article, slide, homework'
        enum:
        - article
        - slide
        - homework
        example: article
        type: string
      title:
        example: 关于后端严谨性的深度思考
        type: string
    required:
    - author
    - category
    - content
    - defaultMode
    - title
    type: object
  article.ErrorResponse:
    properties:
      error:
        example: 参数校验失败
        type: string
    type: object
  asset.SuccessResponse:
    properties:
      id:
        type: integer
      url:
        type: string
    type: object
  upload.ErrorResponse:
    properties:
      error:
        example: 错误描述
        type: string
    type: object
  upload.UploadResponse:
    properties:
      id:
        example: 1
        type: integer
      message:
        example: 上传成功
        type: string
      url:
        example: /uploads/images/2026/03/25/uuid.png
        type: string
    type: object
info:
  contact: {}
paths:
  /articles:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/article.ArticleListResponse'
      summary: 获取文章列表
      tags:
      - Articles
    post:
      consumes:
      - application/json
      parameters:
      - description: 文章内容
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/article.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: '{"id": "uuid"}'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/article.ErrorResponse'
      summary: 发布新文章
      tags:
      - Articles
  /articles/{id}:
    get:
      parameters:
      - description: 博客ID
        example: '"1"'
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/article.Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/article.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/article.ErrorResponse'
      summary: 获取特定 ID 的博客
      tags:
      - 博客接口
  /assets:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/asset.SuccessResponse'
      summary: 上传资源
      tags:
      - 资源接口
  /upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/upload.UploadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/upload.ErrorResponse'
      summary: 上传资源文件
      tags:
      - 资源接口
swagger: "2.0"
